// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD80R39_ZGoniR9UF0HuYYWeW6tWxsrIcM',
    appId: '1:181825447266:web:c781e47537ea3fd60e383b',
    messagingSenderId: '181825447266',
    projectId: 'databaseclass3-690fc',
    authDomain: 'databaseclass3-690fc.firebaseapp.com',
    storageBucket: 'databaseclass3-690fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXvUIySHOr5f2wVzAoQROHPEIyG_dNkZ4',
    appId: '1:181825447266:android:203d0e264cf7affe0e383b',
    messagingSenderId: '181825447266',
    projectId: 'databaseclass3-690fc',
    storageBucket: 'databaseclass3-690fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBIMIxhYii3Iv6SE3m-W_oYR8C0meVyRU',
    appId: '1:181825447266:ios:56b764b9123837a60e383b',
    messagingSenderId: '181825447266',
    projectId: 'databaseclass3-690fc',
    storageBucket: 'databaseclass3-690fc.appspot.com',
    iosBundleId: 'com.example.sqlcheatcode',
  );
}
